### ISSUE TITLE
Total meltdown

### ISSUE THREAD

**Issue by SunGg12138** [braintree/braintree_express_example#21]
npm test, error!

Cannot find module 'eslint-config-braintree/server'
Referenced from: /Users/mac/Desktop/braintree_express_example/.eslintrc
Error: Cannot find module 'eslint-config-braintree/server'
Referenced from: /Users/mac/Desktop/braintree_express_example/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:584:26)
    at configExtends.reduceRight (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:182:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! braintree_express_example@0.0.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the braintree_express_example@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2017-09-16T00_26_36_428Z-debug.log
npm ERR! Test failed.  See above for more details.

```
npm install eslint-config-braintree --save 
```
Or error

npm start error!
> braintree_express_example@0.0.0 start /Users/mac/Desktop/braintree_express_example
> node ./bin/www

{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.config (/Users/mac/Desktop/braintree_express_example/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/Users/mac/Desktop/braintree_express_example/lib/gateway.js:6:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
/Users/mac/Desktop/braintree_express_example/lib/gateway.js:7
environment = process.env.BT_ENVIRONMENT.charAt(0).toUpperCase() + process.env.BT_ENVIRONMENT.slice(1);
                                        ^

TypeError: Cannot read property 'charAt' of undefined
    at Object.<anonymous> (/Users/mac/Desktop/braintree_express_example/lib/gateway.js:7:41)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mac/Desktop/braintree_express_example/routes/index.js:6:15)
    at Module._compile (module.js:573:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! braintree_express_example@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the braintree_express_example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2017-09-16T00_30_01_208Z-debug.log

**Comment by crookedneighbor** [comment]
> Cannot find module 'eslint-config-braintree/server'

This should indicate that you did not run `npm install`. If that is not the case, we'll need to know more information about your set up. (OS, npm version, node version, etc)

> { Error: ENOENT: no such file or directory, open '.env'
at Object.fs.openSync (fs.js:652:18)
at Object.fs.readFileSync (fs.js:553:33)
at Object.config 

Indicates that you didn't include a .env file. Please follow the setup instructions: https://github.com/braintree/braintree_express_example#setup-instructions

Going to close this now, but if you're still having issues, please feel free to comment.
