### ISSUE TITLE
clientToken issue

### ISSUE THREAD

**Issue by deni6052** [braintree/braintree_express_example#33]
I get this output in conosole when i try to load the app in my browser: 

TypeError: Cannot read property 'clientToken' of undefined
    at /Users/deni/Downloads/braintree_express_example-master/routes/index.js:57:56
    at Timeout._onTimeout (/Users/deni/Downloads/braintree_express_example-master/node_modules/@braintree/wrap-promise/lib/deferred.js:10:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by hollabaq86** [comment]
Hi @deni6052 please contact [Braintree Support](https://help.braintreepayments.com/) for assistance, they'll be able to help you troubleshoot the issue.
