### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by Gaseema** [braintree/braintree_express_example#35]
Run the code as per the document and got the error below

 braintree_express_example@0.0.0 start /home/gaz/Downloads/braintree_express_example-master
> node ./bin/www

/home/gaz/Downloads/braintree_express_example-master/lib/gateway.js:7
environment = process.env.BT_ENVIRONMENT.charAt(0).toUpperCase() + process.env.BT_ENVIRONMENT.slice(1);
                                         ^

TypeError: Cannot read property 'charAt' of undefined
    at Object.<anonymous> (/home/gaz/Downloads/braintree_express_example-master/lib/gateway.js:7:42)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/gaz/Downloads/braintree_express_example-master/routes/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! braintree_express_example@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the braintree_express_example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gaz/.npm/_logs/2019-07-23T06_13_37_916Z-debug.log

**Comment by crookedneighbor** [comment]
For future reference, this was likely because the env variables were not set.
